ytest manual
============
Rodolphe Saugier <rodolphe.saugier@gmail.com>
v1.0

Introduction
------------

Summary
~~~~~~~

yTest is a PHP 5 library extending PHPUnit, leveraging the power of the runkit extension
to allow stubbing/mocking things that can't easily changed otherwise:

- private methods.
- static methods.
- functions, including built-in PHP functions.

*ytest* has been used in a test suite of a real world project, so you can trust it
(even if some parts still need some polish obviously).

[[isolation]]
Isolation in automated testing
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When writing automated tests to a project, you need to *isolate* the code
you are testing (often called *SUT*, System Under Test) from other parts of 
the whole system that it depends on (often called *DOC*, Depended-on component).

The SUT can be anything from a method, class, or whole application, depending on
the kind of tests you are writing (unit tests, integration tests, functional tests...).

To isolate the SUT, the DOCs dependencies must be replaced by other "fake" objects
during the automated test. These dummy objects/functions can be configured to return
whatever the SUT needs to work.
Replacing a function or method by a test version is often called "stubbing" or "mocking"
(if it isn't "faking" !).

[NOTE]
=========================================================================================================
Some definitions:

- A *stub* is a static object version designed specifically for a test, returning hard-coded values
specific to the test. 
- A *mock object* is a more elaborate fake object which can be configured to dynamically return values
expected by the SUT during the test, but which can also verify the calls made to it by the SUT.
=========================================================================================================

In a system designed up-front to be tested automatically, there are standard techniques
to help replacing the DOCs by their test versions. The most common is *dependency injection*,
which helps achieve *IOC* (Inversion of Control). The basic principle is easy:
Each dependency of each component of the whole system must be configurable at runtime.
Dependency injection frameworks help achieving this by expliciting all dependencies
in a configuration file.

If you are building a system from scratch, and want to test it automatically,
you probably want to follow IOC principles from the beginning to allow component isolation.
But for legacy systems, there is often no easy way to achieve isolation. This is where
libraries such as runkit and ytest kick in.

The case of PHP
~~~~~~~~~~~~~~~

In most scripting languages, it is possible to redirect at runtime any private method
or function.
For obscure (?) reasons, this is not possible in PHP, which tries to mimic strongly
typed languages in these aspects. You can't rebind an instance method or function
in PHP as you can do it, for example, in Python, where functions are first-class objects:

--------------------------------------------------------------------------------
def myPythonFunction():
    return 42

def someOtherPythonFunction():
    return "foo"

myPythonFunction=someOtherPythonFunction
--------------------------------------------------------------------------------

Hopefully, brave people have created the *runkit* extension which allows to do
such magic things in PHP as well.

*ytest* is a rather simple library built on top of runkit, which makes it easier
to use with *phpunit* tests (If you ever don't know *phpunit*, it's simply the best
implementation of the *xUnit* family of tools for PHP).

Use cases for ytest
~~~~~~~~~~~~~~~~~~~

- *ytest* is mainly useful for testing existing systems that have not been automatically tested yet,
  and therefore have not been designed to be tested easily (see <<isolation>>).
  +
  "Test after", by contrast with "TDD" (Test driven development), is not fun, but *ytest* makes it easier.
- It can also be useful for new projects if you don't want to rely on heavy dependency injection techniques,
  which sometimes complicate the code a bit. You'll loose the strong typing advantages of dependency injection
  if you choose the *ytest* way, however (since *ytest* uses strings to reference existing methods and properties
  in your code). 
- If your project uses static methods a lot (for performance maybe?), *ytest* will be helpful to test it.
- If your project uses reference parameters ("&output") to return values, *ytest* will be very helpful!

Setting up ytest and its dependencies
-------------------------------------

Requirements
~~~~~~~~~~~~

 - PHP >= 5.2 on GNU/Linux
 - PHPUnit >= 3.4.12
 - runkit ( Actually, the fork which works, by D.Zenovich  https://github.com/zenovich/runkit )
 - MySQL 5 as an optional dependency (required for ytest's sample)

Make ytest's sample work in your PHP environment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Unzip
^^^^^

Extract ytest's archive in some folder, say "/home/foo/libs/ytest".
You get something like this:

--------------------------------------
  -- ytest
     |-- config
     |-- docs
     |-- tests
     `-- libs
         `-- ytest
--------------------------------------

Install PHPUnit
^^^^^^^^^^^^^^^

Install PHPUnit >= 3.4.12 if you haven't already.  
Assuming PHPUnit's phpunit.php lies in /home/foo/libs/phpunit,
make a symbolic link so that ytest can find it:

  $ cd /home/foo/ytest
  $ ln -s /home/foo/libs/phpunit libs/phpunit

Install runkit
^^^^^^^^^^^^^^

Install the excellent version of runkit by Dmitry Zenovich,
which has great bugfixes included.

You can take the latest version here:
    https://github.com/zenovich/runkit/downloads

You'll have to build runkit yourself, and install it as a PHP extension 
in your system. Here's a quick summary of how to do it (which might be outdated):

-----------------------------------------
  $ cd runkit-1.0.3
  $ phpize
  $ ./configure
  $ make
  $ sudo make install
  $ sudo nano /etc/php5/cli/php.ini
-----------------------------------------

With some editor, add the following lines at the end of your php.ini (for CLI since
the unit tests will be run on the command line):
    
--------------------------------
  extension=runkit.so
  runkit.internal_override=1
--------------------------------

Setup MySQL
^^^^^^^^^^^

Setup a test database in MySql, or ytest's main self-test won't work:

- Create a database named "ytest".

- Create a user named "ytest" with full privileges on the "ytest" database.

Test ytest
^^^^^^^^^^

You should be able to run ytest's example test like this:
    $ cd /home/foo/ytest
    $ ./run_tests

You should see something like this:

--------------------------------------------------------
    PHPUnit 3.4.12 by Sebastian Bergmann.

    ...............................

    Time: 0 seconds, Memory: 4.75Mb

    OK (31 tests, 48 assertions)
-------------------------------------------------------

This means that ytest's sample test, tests/FooBarTest.php,
has been executed correctly.
(You can take a look at this test, but it's a bit boring,
you'll probably be better with the ytest docs.)


[[integrating_ytest]]
Integrating ytest with your own test suite
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Now that ytest is functional on your PHP system,
there are two cases:

- If you have no unit tests yet, you can simply add more test files
  along FooBarTest.php in ytest/tests to test your own stuff.
  To access the ytest extensions from your test cases, you simply
  have to make your test cases inherit from yTest_CustomTestCase.
  To run your tests, use the run_tests script.

- If you already have a test suite (and maybe some 
  helper scripts around), you may either:

  * Simply put all your existing test files in ytest/tests,
    and see if it works and suits you. This is the easy way.

  * Or, integrate only the bare ytest library in your system,
    by putting ytest/libs/ytest in your PHP include path.
    In this case you'll have to require the main ytest file
    from your test scripts, for example like this:
+
--
-------------------------------------------------------------------------------------
require_once 'ytest/libs/ytest/ytest.php';
-------------------------------------------------------------------------------------
Then you'll have to initialize ytest at the beginning
of your test suite (like what is done in ytest/Bootstrap.php),
something like this:
-------------------------------------------------------------------------------------
yTest_init("ytest/config/ytest_config.php",   // path to your config file for ytest
	   "ytest/libs/ytest",                // path to the ytest library folder
           "ytest/libs/phpunit"               // path to PHPUnit
          );
-------------------------------------------------------------------------------------
You'll have to tune the folders (and probably use absolute paths).
--

Using ytest
-----------

Getting started
~~~~~~~~~~~~~~~

After you have integrated ytest in your PHP unit test suite (see <<integrating_ytest, ytest integration chapter>>),
using it becomes very easy.
You simply need to make your test classes inherit from *yTest_CustomTestCase*:

---------------------------------------------------------
class FooBarTest extends yTest_CustomTestCase {
    public function testSomething() {
        // test stuff
    }
}
---------------------------------------------------------

yTest_CustomTestCase exposes almost all of ytest functionality through its instance methods.

[WARNING]
================================================================================
If you override setUp() and tearDown() in a test deriving from yTest_CustomTestCase,
make sure to call the parent methods in each case:

---------------------------------------------------------
class FooBarTest extends yTest_CustomTestCase {
    public function setUp() {
        parent::setUp(); // set up ytest stuff!
        // set up your stuff
    }

    public function tearDown() {
        // tear down your stuff
        parent::tearDown(); // tear down ytest stuff!
    }

    public function testSomething() {
        // test stuff
    }
}
---------------------------------------------------------
================================================================================

[NOTE]
================================================================================
yTest does not uses PHP namespaces, for compatibility with legacy stuff.
All symbols declared by ytest start by one of these prefixes:

- *yTest_*
- *ytx_*
================================================================================

Accessing private members
~~~~~~~~~~~~~~~~~~~~~~~~~

Explicit access with letMeCall and letMeAccess
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Suppose we have a simple class with private methods and members:

---------------------------------------------------------

class Foo
{
    private $baz = 42;

    private function bar($arg)
    {
        return $baz * $arg;
    }
}

---------------------------------------------------------

To access baz and bar() in our test, we use letMeCall() and letMeAccess():

---------------------------------------------------------
class FooBarTest extends yTest_CustomTestCase {

    public function testBarBaz() {
        $this->letMeCall("FooBar", "bar");    // see <1>
        $this->letMeAccess("FooBar", "baz");  // see <2>

        $foobar = new FooBar();

        $this->assertEquals(42, $this->getProperty($foobar, "baz");  // see <3>
        $this->setProperty($foobar, "baz", 43);

        $this->assertEquals(86, $foobar->ytx_call_bar(2));  // see <4>
    }
}
---------------------------------------------------------

<1> *letMeCall(className, methodName)* allows you to call a private/protected instance
    or static method indirectly for the scope of the current test.
<2> *letMeAccess(className, fieldName)* allows you to access private/protected fields
    indirectly for the scope of the current test.
<3> To get/set a private or protected field, use *setProperty()* and *getProperty()*
    after calling letMeAccess()
<4> To call a private/protected method, use the automatically generated proxy method
    *ytx_call_originalMethodName*.

Of course, letMeCall() and letMeAccess() lets you access fields and methods for *all*
instances of a given class. It is not yet possible to restrict the access to a 
specific instance.

Since the effect of letMeCall() or letMeAccess() remains during the current test,
it is a good practice to put these in the *setUp()* method of your test class.
We can therefore rewrite the preceding example this way:

----------------------------------------------------------

class FooBarTest extends yTest_CustomTestCase {

    public function setUp() {
        parent::setUp();
        $this->letMeCall("FooBar", "bar");
        $this->letMeAccess("FooBar", "baz");
    }

    public function testBarBaz() {
        $foobar = new FooBar();

        $this->assertEquals(42, $this->getProperty($foobar, "baz");
        $this->setProperty($foobar, "baz", 43);

        $this->assertEquals(86, $foobar->ytx_call_bar(2));
    }
}

---------------------------------------------------------- 

You can also use letMeCall() and letMeAccess() on static fields and methods,
but the way to do it changes for a few details:

---------------------------------------------------------

class Foo
{
    private static $staticBaz = 42;

    private static function staticBar($arg)
    {
        return $baz * $arg;
    }
}

class FooBarTest extends yTest_CustomTestCase {

    public function setUp() {
        parent::setUp();
        $this->letMeCall("FooBar", "staticBar");
        $this->letMeAccess("FooBar", "staticBaz");
    }

    public function testBarBaz() {
        $foobar = new FooBar();

        $this->assertEquals(42, $this->getStaticProperty($foobar, "staticBaz");   // see <1>
        $this->setStaticProperty($foobar, "staticBaz", 43);

        $this->assertEquals(86, FooBar::ytx_call_staticBar(2));   // see <2>
    }
}

---------------------------------------------------------

<1> After calling letMeAccess() the same way as for instance fields,
you have to use *getStaticProperty* and *setStaticProperty* instead
of *getProperty* and *setProperty*.
<2> To call the private static method, use the generated static proxy
    *ytx_call_staticBar* on the class.

[NOTE]
================================================================================
letMeCall() and letMeAccess() can be called safely multiple times for the same 
methods or fields. The redundant calls are simply ignored. 
================================================================================

[[proxy_accessors]]
[NOTE]
================================================================================
Internally, letMeAccess() also generates some getter and setter methods
that are actually called by getProperty() and setProperty() to set
the target field.

For an instance field called "fooBar" in a class "Foo" these proxies are:

- *ytx_get_fooBar() -> value*
- *ytx_set_fooBar(value)*

For a static field "fooBar" the proxies are:

- *Foo::ytx_getStatic_fooBar() -> value*
- *Foo::ytx_setStatic_fooBar(value)*

You probably wonder why there is no equivalent of the setProperty()
for calling ytx_call_methodName(), like some "callPrivateMethod()" helper.
Actually, writing a generic method like this seems difficult in PHP,
the problem being the handling of reference parameters.
================================================================================

[WARNING]
================================================================================
ytest uses the magic prefix *ytx_* for all its automatically generated proxy methods.
If your project uses this prefix, you are not completely doomed yet:
you'll have to change it manually in yTest_AbstractCodeChange.php in ytest's sources!
================================================================================

Automatic property access with get/set[Static]Property
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In the previous examples, we used *letMeAccess* to allow private property access.
This has the advantage of making the special private property access explicit,
in a declarative way.

*ytest* also offers the simpler option of accessing private and protected fields directly
by calling *get/setProperty()* and *get/setStaticProperty()* explicitely,
as in the following example:

----------------------------------------------------------

class Foo
{
    private $baz = 42;
    private static $staticBaz = 42;
}

class FooBarTest extends yTest_CustomTestCase {

    public function testFooBar() {
        $foobar = new FooBar();

        $this->assertEquals(42, $this->getProperty($foobar, "baz");
        $this->setProperty($foobar, "baz", 43);

        $this->assertEquals(42, $this->getStaticProperty($foobar, "staticBaz");
        $this->setStaticProperty($foobar, "staticBaz", 43);
    }
}

---------------------------------------------------------- 

[NOTE]
================================================================================
This feature is implemented simply:
*getProperty(), setProperty(), getStaticProperty() and setStaticProperty()* all
do a preventive call to *letMeAccess()* when called.

If you do use the <<proxy_accessors,proxy methods>> directly, you should make
the call to *letMeAccess* explicit for readability.
================================================================================

[NOTE]
================================================================================
*getProperty(), setProperty(), getStaticProperty() and setStaticProperty()*
can be called on public properties too, without problem.
================================================================================

Rewiring methods
~~~~~~~~~~~~~~~~

Method "rewiring" in ytest simply means to rebind it dynamically to another method.
With ytest, you can rewire any class method (static or instance) and any function
to a *public instance method of another object*.
Rewiring to a function is not supported, but is not really needed, since you
can always write some class to achieve what you need.

Rewiring an instance method
^^^^^^^^^^^^^^^^^^^^^^^^^^^

Here is a simple example of rewiring an *instance method* to another *instance method*,
supposing we want to isolate the system under testd "Foo" from its dependency
"FooDependency" (see the chapter on <<isolation>> for the philosophy behind this).

--------------------------------------------------------------------------------

class Foo
{
    public function doStuff()
    {
        $dep = new Dependency();
        return $dep->bar(2);
    }
}

class Dependency
{
    private $baz = 40;

    private function bar($arg)
    {
        return $baz + $arg;
    }
}

class DummyDependency
{
    public function dummyBar()
    {
        return 38;
    }
}

class FooBarTest extends yTest_CustomTestCase {

    public function testFoo() {
        $foo = new Foo();
        $this->assertEquals(42, $foo->doStuff());   // the original method gets called, we get 40 + 2 = 42

        // now rewire bar()
        $dummy = new DummyDependency();
        $this->rewireMethod("FooDependency", "bar", $dummy, "dummyBar");
        $this->assertEquals(38, $foo->doStuff());   // dummy version gets called
        $this->assertEquals(38, $foo->doStuff());   // dummy version still gets called
    }
}

-------------------------------------------------------------------------------

*rewireMethod(className, originalMethodName, dummyInstance, dummyMethodName)* takes 3 or 4 parameters:

className::
The name of the class containing the original method to be rewired.
+
(This argument can also be an object instance, details are explained <<rewiring_specific,further>>).

originalMethodName::
The name of the original method to be rewired.

dummyInstance::
An *object instance* which exposes the dummy method.

dummyMethodName::
The name of the dummy method, which will receive the calls *instead of* the original method.
+
This 4th argument is actually optional: If you omit it, ytest will assume that the 
dummy method has the same name as the original method.

Rewiring a static method
^^^^^^^^^^^^^^^^^^^^^^^^

*rewireMethod* can be used on static methods as well.
Actually, the same arguments in the preceding example work for a static method.

--------------------------------------------------------------------------------

class Foo
{
    public function doStuff()
    {
        return Dependency::bar(2);
    }
}

class Dependency
{
    private $baz = 40;

    private static function bar($arg)
    {
        return $baz + $arg;
    }
}

class DummyDependency
{
    public function dummyBar() // see <1>
    {
        return 38;
    }
}

class FooBarTest extends yTest_CustomTestCase {

    public function testFoo() {
        $foo = new Foo();
        $this->assertEquals(42, $foo->doStuff());   // the original static method gets called, we get 40 + 2 = 42

        // now rewire bar()
        $dummy = new DummyDependency();
        $this->rewireMethod("FooDependency", "bar", $dummy, "dummyBar"); // see <2>
        $this->assertEquals(38, $foo->doStuff());   // dummy static method gets called
        $this->assertEquals(38, $foo->doStuff());   // dummy static method still gets called
    }
}

-------------------------------------------------------------------------------
<1> When rewiring a static method, you still have to rewire it to an instance method.
<2> This is the same call as in the previous example, it works for a static method too.

[[rewiring_specific]]
Rewiring an instance method of a specific instance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Although rarely useful, ytest supports rewiring an instance method of a specific instance:

--------------------------------------------------------------------------------

class Foo
{
    public function doStuff()
    {
        $dep = new Dependency();
        return $dep->bar(2);
    }
}

class Dependency
{
    private $baz = 40;

    private function bar($arg)
    {
        return $baz + $arg;
    }
}

class DummyDependency
{
    public function dummyBar()
    {
        return 38;
    }
}

class FooBarTest extends yTest_CustomTestCase {

    public function testFoo() {
        $foo1 = new Foo();
        $this->assertEquals(42, $foo1->doStuff());   // the original method gets called, we get 40 + 2 = 42

        // now rewire bar()
        $dummy = new DummyDependency();
        $this->rewireMethod($foo1, "bar", $dummy, "dummyBar");   // we rewire "bar" on a *specific* instance: $foo1
        $this->assertEquals(38, $foo1->doStuff());               // dummy version gets called for $foo1

        $foo2 = new Foo();
        $this->assertEquals(42, $foo2->doStuff());   // For $foo2, the original method gets called, we get 40 + 2 = 42
    }
}

As you can see, only $foo1 is affected by the rewiring: Other instances are unchanged.

-------------------------------------------------------------------------------

Notes on method rewiring
^^^^^^^^^^^^^^^^^^^^^^^^

- Rewiring takes effect just after the call to *rewireMethod*.
  Unless rewiring a specific instance, all existing and future instances are affected.

- Rewiring lasts from the call to *rewireMethod* til the end of the test method.

- Rewiring static methods is specially useful: It is impossible to do it with bare PHPUnit.

- A good place to store your dummy functions is in the test class itself.

- Rewiring a specific instance is rarely useful, you'll prefer class-wide rewiring at most times.

- As for *letMeCall* and *letMeAccess*, calls to *rewireMethod* may be put in your *setUp()* methods,
  so that rewiring affects all the tests of the test class.

- It is of course a good idea to rewire existing methods to PHPUnit mock objects.
  Actually some helpers in *yTest_CustomTestCase* exist to create PHPUnit mocks on the
  fly for functions and static methods: *mockFunction()* and *mockStaticMethod()*.
  I won't detail them now however, since their use has always been a bit experimental,
  so you'll have to check their definition if you're interested!

- You can rewire methods or functions with reference arguments, this is actually
one strength of *ytest* (thanks to *runkit* of course!). Here's an example with
a static method:

--------------------------------------------------------------------------------

class Foo
{
    private static function bar(&$output)
    {
        $output = "bar";
    }
}

class FooBarTest extends yTest_CustomTestCase {

    public function dummyBar(&output)
    {
        $output = "foo";
    }

    public function testFoo() {
        Foo::bar($out);
        $this->assertEquals("bar", $out);

        // now rewire bar()
        $this->rewireMethod("Foo", "bar", $this, "dummyBar");

        Foo::bar($out2);
        $this->assertEquals("foo", $out2);
    }
}

--------------------------------------------------------------------------------

Rewiring functions
~~~~~~~~~~~~~~~~~~

Like methods, user functions can be rewired to *specific instance methods* as well:

--------------------------------------------------------------------------------

function bar()
{
    return 42;
}

class Dummy
{
    public function dummyBar()
    {
        return 38;
    }
}

class FooBarTest extends yTest_CustomTestCase {

    public function testBar() {
        $this->assertEquals(42, bar());   // the original function gets called

        // now rewire bar()
        $dummy = new Dummy();
        $this->rewireFunction("bar", $dummy, "dummyBar");   // we rewire "bar" to $dummy->dummyBar()
        $this->assertEquals(38, bar());
    }
}

--------------------------------------------------------------------------------

[WARNING]
================================================================================
Rewiring a function to another function is unsupported yet!
However, it is very convenient to rewire a function to a function in the current
test class. We can rewrite the previous example this way:

--------------------------------------------------------------------------------
class FooBarTest extends yTest_CustomTestCase {

    public function dummyBar() {
        return 38;
    }

    public function testBar() {
        $this->assertEquals(42, bar());   // the original function gets called
        $this->rewireFunction("bar", $this, "dummyBar");   // we rewire "bar" to $this->dummyBar()
        $this->assertEquals(38, bar());
    }
}
--------------------------------------------------------------------------------

================================================================================

*rewire_function(originalFunctionName, dummyInstance, dummyMethodName)* has three parameters:

originalFunctionName::
    This is the name of the function to be rewired.

dummyInstance::
    This is the instance containing the target dummy method.

dummyMethodName::
    This is the target dummy method name!

Thanks to runkit, it is also possible to rewire internal PHP functions,
like "mt_rand" for example:

--------------------------------------------------------------------------------
class FooBarTest extends yTest_CustomTestCase {

    public function fixedRand() {
        return 38;
    }

    public function testMtRand() {
        $this->rewireFunction("mt_rand", $this, "fixedRand");
        $this->assertEquals(38, mt_rand());
    }
}
--------------------------------------------------------------------------------

[NOTE]
================================================================================
Stubbing functions like *mt_rand* and *time* is essential in your tests,
to make their execution deterministic.
================================================================================

Changing constants
^^^^^^^^^^^^^^^^^^

You can change the value of a constant during the execution of a test method.
This works for global constants and class constants as well:

--------------------------------------------------------------------------------

const HALF = 21;

class Foo
{
    const TOTAL = 42;
}

class FooBarTest extends yTest_CustomTestCase {

    public function testConstants() {
        $this->assertEquals(21, HALF);
        $this->assertEquals(42, Foo::TOTAL);

        $this->setConstant("HALF", 1);
        $this->assertEquals(1, HALF);

        $this->setClassConstant("Foo", "TOTAL", 2);
        $this->assertEquals(2, TOTAL);
    }
}

--------------------------------------------------------------------------------

Like other changes controlled by ytest, the change only lasts for the current test method.
Like all other changes, putting *setConstant* and *setClassConstant* calls in *setUp*
may be a good idea.

Other ytest features
~~~~~~~~~~~~~~~~~~~~

*ytest* has a few other features, which can be useful sometimes.
We'll document here those that should be the more interesting:

Undoing changes
^^^^^^^^^^^^^^^

If you need to undo a rewiring, or another change, before the end of the current test
method, you can use the fact that *rewireXXX* and other methods that change the return
a *code change* object.
Here's an example with *rewireFunction*:

--------------------------------------------------------------------------------
function bar()
{
    return 42;
}

class FooBarTest extends yTest_CustomTestCase {

    public function dummyBar() {
        return 38;
    }

    public function testBar() {
        $this->assertEquals(42, bar());   // the original function gets called
        $codeChange = $this->rewireFunction("bar", $this, "dummyBar");   // we rewire "bar" to $this->dummyBar()
        $this->assertEquals(38, bar());
        $this->undoChange($codeChange);
        $this->assertEquals(42, bar());   // the original function gets called, before the end of the test.
    }
}
--------------------------------------------------------------------------------

Methods that return *code changes* (actually *yTest_AbstractCodeChange* instances)
are the following:

- *rewireMethod*
- *rewireFunction*
- *unwireMethod*
- *letMeCall*
- *letMeAccess*
- *setConstant*
- *setClassConstant*

[NOTE]
================================================================================
Internally, yTest uses a stack of code changes, that all get reverted at 
the end of the current test method. This is what allows the isolation of
code changes made by runkit to one test method only.
================================================================================

Output buffering
^^^^^^^^^^^^^^^^

*ytest* makes output buffer recording easy:

--------------------------------------------------------------------------------

class FooBarTest extends yTest_CustomTestCase {

    public function testOutput() {
        $this->recordOutput();
        echo "hello";
        $output = $this->stopRecordOutput();
        $this->assertEquals("hello", $output);
    }
}

--------------------------------------------------------------------------------

If you forget to call *stopRecordOutput* or if the test fails, *ytest* will undo output buffering
for you at the end of the test.

Debug output
^^^^^^^^^^^^

- You can use *yTest_dbg("blah", "blah", ...)* to output debug stuff immediately to the console,
bypassing output buffering. This can come handy in situations where you don't understand
what your tests are doing.

- *yTest_dbgStack()* prints the current detailled stack, using yTest_dbg().

- *yTest_dbgx(item1, item2, ...)* prints var_export(item1, true), var_export(item2, true)... using yTest_dbg().
